name: RunUnitTest

on: pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libmpfr-dev

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build tests
      working-directory: test
      run: |
        make -k -j`nproc` build

    - name: Run tests
      working-directory: test
      run: |
        make -k run
