name: RunUnitTest

on: pull_request

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - cms-patatrack-h100
          - cms-patatrack-l40s
          - cms-patatrack-mi300x
          - cms-patatrack-w7900
    runs-on: ${{ matrix.runner }}
    container: registry.cern.ch/ngt/lxplus-like:9

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build tests
        working-directory: test
        run: |
          source /cvmfs/projects.cern.ch/intelsw/oneAPI/linux/x86_64/2025/setvars.sh
          make \
            CUDA_BASE=/cvmfs/patatrack.cern.ch/externals/x86_64/rhel9/nvidia/cuda-12.9.1 \
            ROCM_BASE=/cvmfs/patatrack.cern.ch/externals/x86_64/rhel9/amd/rocm-7.1.0 \
            ONEAPI_BASE=/cvmfs/projects.cern.ch/intelsw/oneAPI/linux/x86_64/2025 \
            -k -j`nproc` build

      - name: Run tests
        working-directory: test
        run: |
          source /cvmfs/projects.cern.ch/intelsw/oneAPI/linux/x86_64/2025/setvars.sh
          make \
            CUDA_BASE=/cvmfs/patatrack.cern.ch/externals/x86_64/rhel9/nvidia/cuda-12.9.1 \
            ROCM_BASE=/cvmfs/patatrack.cern.ch/externals/x86_64/rhel9/amd/rocm-7.1.0 \
            ONEAPI_BASE=/cvmfs/projects.cern.ch/intelsw/oneAPI/linux/x86_64/2025 \
            -k run
